services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "OrderDesk!Pass123"
    ports: ["1433:1433"]
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'OrderDesk!Pass123' -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver: { condition: service_healthy }
    entrypoint: ["/bin/bash", "-c"]
    command:
      - /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'OrderDesk!Pass123' -C -i /sql/create-db.sql
    volumes: ["./sql:/sql:ro"]

  redpanda:
    image: redpandadata/redpanda:v24.2.7
    command:
      - redpanda start --smp 1 --memory 1G --overprovisioned --node-id 0
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports: ["19092:19092"]
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -q 'Healthy:.*true'"]
      interval: 10s
      timeout: 5s
      retries: 20

  console:
    image: redpandadata/console:v2.7.2
    depends_on: [redpanda]
    environment:
      KAFKA_BROKERS: redpanda:9092
    ports: ["8085:8080"]

  jaeger:
    image: jaegertracing/all-in-one:1.60
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports: ["16686:16686", "4317:4317", "4318:4318"]

  order-service:
    build: ../services/order-service
    depends_on:
      db-init: { condition: service_completed_successfully }
      redpanda: { condition: service_healthy }
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=orderdesk;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "OrderDesk!Pass123"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_SERVICE_NAME: order-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    ports: ["8080:8080"]

  inventory-service:
    build: ../services/inventory-service
    depends_on:
      order-service: { condition: service_started }
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://sqlserver:1433;databaseName=orderdesk;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: "OrderDesk!Pass123"
      SPRING_KAFKA_BOOTSTRAP_SERVERS: redpanda:9092
      OTEL_SERVICE_NAME: inventory-service
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_METRICS_EXPORTER: none
      OTEL_LOGS_EXPORTER: none
    ports: ["8081:8081"]
